#!/usr/bin/bash

ec=$1

# Function to check if a number is prime
is_prime() {
	echo "ENTERED: $1"
	num=$1	
	for ((i = 2; i * i <= num; i++)); do
		if ((num % i == 0)); then
			return 1  # Number is not prime
		fi
	done

	return 0  # Number is prime
}

is_prime $ec

echo "result: $?"
